"""Backtest-compatible re-export of the shared execution commission model."""

from quant.runtime.execution_commission import (
    CN_COMMISSION_RATE,
    CN_EXCHANGE_TRADED_FUND_PREFIXES,
    CN_FUND_COMMISSION_RATE,
    CN_FUND_MIN_COMMISSION,
    CN_MIN_COMMISSION,
    CN_REGULATOR_FEE_RATE,
    CN_STAMP_DUTY_RATE,
    CN_STAMP_DUTY_RATE_HISTORY,
    CN_TRANSFER_FEE_RATE,
    HK_CLEARING_RATE,
    HK_COMMISSION_RATE,
    HK_MIN_COMMISSION,
    HK_SFC_LEVY_RATE,
    HK_STAMP_DUTY_RATE,
    HK_STAMP_DUTY_RATE_HISTORY,
    HK_TRADING_FEE_RATE,
    HK_TRADING_SYSTEM_FEE,
    US_FINRA_TAF_PER_SHARE,
    US_SEC_FEE_RATE,
    VOLUME_PARTICIPATION_LIMIT,
    _calculate_cn_commission,
    _calculate_cn_fund_commission,
    _calculate_hk_commission,
    _calculate_us_commission,
    _get_market_config,
    calculate_commission,
    get_rate_for_date,
    total_commission,
)


__all__ = [
    "CN_COMMISSION_RATE",
    "CN_EXCHANGE_TRADED_FUND_PREFIXES",
    "CN_FUND_COMMISSION_RATE",
    "CN_FUND_MIN_COMMISSION",
    "CN_MIN_COMMISSION",
    "CN_REGULATOR_FEE_RATE",
    "CN_STAMP_DUTY_RATE",
    "CN_STAMP_DUTY_RATE_HISTORY",
    "CN_TRANSFER_FEE_RATE",
    "HK_CLEARING_RATE",
    "HK_COMMISSION_RATE",
    "HK_MIN_COMMISSION",
    "HK_SFC_LEVY_RATE",
    "HK_STAMP_DUTY_RATE",
    "HK_STAMP_DUTY_RATE_HISTORY",
    "HK_TRADING_FEE_RATE",
    "HK_TRADING_SYSTEM_FEE",
    "US_FINRA_TAF_PER_SHARE",
    "US_SEC_FEE_RATE",
    "VOLUME_PARTICIPATION_LIMIT",
    "_calculate_cn_commission",
    "_calculate_cn_fund_commission",
    "_calculate_hk_commission",
    "_calculate_us_commission",
    "_get_market_config",
    "calculate_commission",
    "get_rate_for_date",
    "total_commission",
]
